boots: IRON_BOOTS
leggings: IRON_LEGGINGS
chestplate: IRON_CHESTPLATE
helmet: IRON_HELMET

items:
  IRON_SWORD:
  quantity: 1
  enchantments:
    DAMAGE_ALL:
      level: 3
BOW:
  quantity: 1
  enchantments:
    ARROW_DAMAGE:
      level: 3
ARROW:
  quantity: 64
GOLDEN_APPLE:
  quantity: 3
MUSHROOM_STEW:
  quantity: 1
MUSHROOM_STEW:
  quantity: 1
MUSHROOM_STEW:
  quantity: 1
MUSHROOM_STEW:
  quantity: 1
MUSHROOM_STEW:
  quantity: 1
